### ISSUE TITLE
application.properties misses mongodb information

### ISSUE THREAD

**Issue by gewure** [dassiorleando/spring-reactive-mongodb#1]
could you provide a sample config please? :)

**Comment by dassiorleando** [comment]
I'm using the Java config way, you can check it inside the [MongoConfiguration.java](https://github.com/dassiorleando/spring-reactive-mongodb/blob/master/src/main/java/xyz/dassiorleando/springreactivemongodb/MongoConfiguration.java) file with:
- Localhost server with the default mongo port 27017
- spring-reactive-mongodb as the database name
